# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(default='Female', max_length=10)),
                ('description', models.CharField(max_length=140)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=10)),
                ('facebook_account', models.CharField(max_length=100)),
                ('twitter_account', models.CharField(max_length=100)),
                ('is_wholesaler', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('logo_file', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('copyright_message', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('images', models.ManyToManyField(to='register.Image')),
            ],
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.Image'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
